# Generated by Django 6.0.3 on 2026-03-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(max_length=50, verbose_name='Compte')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('quantite', models.FloatField(default=0, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unité')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Spécification')),
                ('observation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observation')),
            ],
        ),
    ]
