# Generated by Django 6.0.3 on 2026-04-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationbudget',
            name='comptes',
        ),
        migrations.AddField(
            model_name='allocationbudget',
            name='sous_compte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.souscompte', verbose_name='Sous-Compte'),
        ),
    ]
