# Generated by Django 6.0.3 on 2026-03-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='compte',
            field=models.CharField(max_length=100, verbose_name='Compte'),
        ),
    ]
