# Generated by Django 6.0.4 on 2026-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbm',
            name='annee_ex',
            field=models.CharField(default='', max_length=50, verbose_name='Code_EX'),
        ),
        migrations.AddField(
            model_name='dbm',
            name='motif',
            field=models.CharField(default='', max_length=255, verbose_name='Motif'),
        ),
    ]
