# Generated by Django 6.0.3 on 2026-04-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_dbm_annee_ex_dbm_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsengagement',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.produit'),
        ),
        migrations.AlterField(
            model_name='bonengagement',
            name='annee_ex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='bonengagement',
            name='comptes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.allocationbudget', verbose_name='Compte Budgétaire'),
        ),
        migrations.AlterField(
            model_name='bonengagement',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='detailsengagement',
            name='budget_ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget', verbose_name='IDbudget'),
        ),
    ]
