# Generated by Django 6.0.3 on 2026-04-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_detailsengagement_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonengagement',
            name='comptes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.allocationbudget', verbose_name='Compte Budgétaire'),
        ),
    ]
