# Generated by Django 6.0.4 on 2026-04-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_alter_bonengagement_comptes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonengagement',
            name='montant_engagement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='bonengagement',
            name='montant_inscrit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='bonengagement',
            name='nombre_articles',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre articles'),
        ),
    ]
